[common_settings]
# 当前是否为调试环境
debug=False
; 是否在机器翻译的译文前添加TODO标记，方便搜索润色。True开启，False关闭
open_todo=True

[filter_texts]
; 专用于RPG，当JSON翻译文本中，文本的值赋成NONE，则工具在写入新的data数据文件时会忽略该文本。最好不要改动，避免后续文本更新不通用。
none_filter=NONE
; 专用于RPG，用于标记不翻译文本，可配置多个标记，使用半角逗号“,”隔开，逗号之间不要留空格。设定好后最好不要删除，避免后续文本更新不通用，如需改动，可以在后面添加新的。
pass_filter=PASS,USELESS

[rpy_trans_tool]
; 待翻提取文本默认所在目录。若留空，则在程序运行时手动输入。翻译完成的提取文本默认存入待翻文本所在父目录，末尾添加'-new'以区分
; rpy_input_abspath=D:\2R-Tools\RenPy Workspace\XXX\chinese
rpy_input_abspath=
; 翻译文本最大缓存数，缓存数达到指定值则进行一次文件写入。程序设定最小值为0，即不缓存，处理一次便写入文件一次（不推荐）
rpy_bap_max_cache=50

[rpy_update_tool]
; 旧提取文本默认所在目录。若留空，则在程序运行时手动输入
rpy_old_abspath=
; rpy_old_abspath=D:\2R-Tools\RenPy Workspace\XXX\chinese
; 新提取文本默认所在目录。若留空，则在程序运行时手动输入。更新完成的提取文本默认存入新提取文本当前所在目录中，末尾添加'-new'以区分
rpy_new_abspath=
; rpy_new_abspath=D:\2R-Tools\RenPy Workspace\XXX\chinese-new
; 待处理区块最大缓存数。程序设定最小值为0，即不缓存，处理一次便写入文件一次（不推荐）
rpy_bap_max_cache=100

[json_trans_tool]
; 翻译最大缓存数。程序设定最小值为0，即不缓存，翻译一次便写入文件一次（不推荐）
json_max_cache=50

[rpgm_extraction_writing]
; rpgm游戏旧翻译文本，将其置入libraries文件夹即可在提取新翻译文件时自动录入已有译文
rpg_game_default_txt=gameText.json
; 扫描白名单
rpg_white_list=Actors,Armors,Classes,CommonEvents,Enemies,Items,Skills,States,System,Troops,Weapons,BattleHUD,MapHUD
; 无需使用标识符区分相同文本的可去重列表
rpg_duplicate_removal_list=Actors,Classes,Enemies,Troops
; array -> object数据结构
rpg_type_array_object=Actors,Armors,Classes,Enemies,Items,Skills,States,Troops,Weapons
; 脚本中有需要显示的文本时，使用正则匹配。可同时匹配多项，使用半角逗号“,”隔开，逗号之间不要留空格
rpg_script_regexp=


; 翻译API接口通行证（敏感内容，请妥善保管）及其他设置，放在这里是为了方便统一管理
; 腾讯翻译
[tencent_api]
; 密钥
secretId=
secretKey=

; 是否启用
activate=False
; 翻译请求频率。次/秒。官方限定5 QPS，设定值最好比官方少一些，留出安全空余
max_qps=4
; 单次请求最大字符数（一个汉字、一个字母、一个标点都计为一个字符）
max_char=2000

; 百度翻译
[baidu_api]
; 密钥
appid=
secretKey=

; 是否启用
activate=False
; 翻译请求频率。次/秒。高级版官方限定10 QPS，设定值最好比官方少一些，留出安全空余
max_qps=8
; 单次请求最大字符数（含符号和空格），依据平台限制设置
max_char=2000

; 彩云小译
[caiyun_api]
; 密钥
token=

; 是否启用
activate=False
; 翻译请求频率。次/秒。官方限定10 QPS，设定值最好比官方少一些，留出安全空余
max_qps=8
; 单次请求最大字符数（含符号和空格），依据平台限制设置
max_char=2000

; DeepL翻译
[deepL_api]
# 密钥
auth_key=

; 是否启用
activate=False
; 翻译请求频率。次/秒
max_qps=1
; 单次请求最大字符数（含符号和空格），依据平台限制设置
max_char=2000

; 谷歌翻译
[google_api]
; 是否启用
activate=False
; 翻译请求频率。次/秒
max_qps=1
; 单次请求最大字符数（含符号和空格），依据平台限制设置
max_char=2000

[huoshan_api]
; 密钥
AccessKeyID=
SecretAccessKey=

; 是否启用
activate=False
; 翻译请求频率。次/秒。官方限定10 QPS，设定值最好比官方少一些，留出安全空余
max_qps=8
; 单次请求最大字符数（含符号和空格），依据平台限制设置
max_char=2000

;小牛翻译
[xiaoniu_api]
; 密钥
APPID=
API_KEY=

; 是否启用
activate=False
; 翻译请求频率。次/秒。官方限定5 QPS，设定值最好比官方少一些，留出安全空余
max_qps=4
; 单次请求最大字符数（含符号和空格），依据平台限制设置
max_char=2000

; 讯飞翻译
[xunfei_api]
; 密钥
APPID=
APISecret=
APIKey=

; 是否启用
activate=False
; 翻译请求频率。次/秒。官方限定10 QPS，设定值最好比官方少一些，留出安全空余
max_qps=8
; 单次请求最大字符数（含符号和空格），依据平台限制设置
max_char=4000

; 有道智云
[youdao_api]
; 密钥
appId=
appKey=

; 是否启用
activate=False
; 翻译请求频率。次/秒
max_qps=1
; 单次请求最大字符数（含符号和空格），依据平台限制设置
max_char=5000

; Ollama框架本地AI翻译
[ollama_api]
; 当前调用模型名称。
model_name=
; model_name=gemma3:4b
; 是否启用Ollama本地AI翻译引擎，默认False关闭，环境部署完成后可True开启
activate=False

; 生成文本时可预测的最大令牌数。官方默认-1，表示无限生成
num_predict=2048
; 模型的温度。提高温度会使模型的回答更具创造性。取值范围：0.0-2.0，官方默认0.8
temperature=0.8
; 替代 top_p参数，旨在确保生成结果在质量与多样性之间取得平衡。参数 p 表示一个词元（token）被考虑的最低概率阈值，该阈值相对于最可能词元的概率。例如，当 p=0.05 且最可能词元的概率为 0.9 时，概率值低于 0.045 的词元将被过滤掉。官方默认0.0
min_p=0.0
; 核采样。与 top-k配合使用。较高的值（例如 0.95）将生成更多样化的文本，而较低的值（例如 0.5）将生成更聚焦、更保守的文本。取值范围：0.0-1.0，官方默认0.9
top_p=0.9
; 降低生成无意义内容的概率。较高的值（例如100）将产生更多样化的答案，而较低的值（例如10）则更加保守。取值范围：1-50，官方默认40
top_k=40
; 设置对重复内容的惩罚强度。数值越高（例如1.5），对重复内容的惩罚越强；数值越低（例如0.9），则越宽松。官方默认1.1
repeat_penalty=1.1
; 设置用于生成的随机数种子。将此值设置为特定数字将使模型对相同的提示生成相同的文本。官方默认0
seed=0

; Transformers框架本地AI翻译
[hunyuan_mt_api]
; 模型的绝对路径
model_path=
; model_path=D:\AI_Projects\Hunyuan-MT\Hunyuan-MT1.5-7B
; model_path=D:\AI_Projects\Hunyuan-MT\HY-MT1.5-1.8B
; 是否启用Hunyuan-MT模型本地AI翻译引擎，默认False关闭，环境部署完成后可True开启
activate=False

; 当内存不足时，可以使用bitsandbytes库来减小模型的内存占用，使得在计算资源有限的情况下也能处理大型模型。
; 选择模型加载量化方式.0: 不启用量化；1: 8bit量化；2: 4bit量化；3: NF4量化；4: 双量化；5: QLoRA量化
load_flag=1
; 新生成 token 数量
max_new_tokens=2048
; 模型的温度。提高温度会使模型的回答更具创造性。取值范围：0.0-2.0，官方默认0.7
temperature=0.7
; 核采样。与 top-k配合使用。较高的值（例如 0.95）将生成更多样化的文本，而较低的值（例如 0.5）将生成更聚焦、更保守的文本。取值范围：0.0-1.0，官方默认0.6
top_p=0.6
; 降低生成无意义内容的概率。较高的值（例如100）将产生更多样化的答案，而较低的值（例如10）则更加保守。取值范围：1-50，官方默认20
top_k=20
; 设置对重复内容的惩罚强度。数值越高（例如1.5），对重复内容的惩罚越强；数值越低（例如0.9），则越宽松。官方默认1.05
repetition_penalty=1.05
